
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Vikrant Rana
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CB1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        off1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        point1 = new javax.swing.JLabel();
        point1.setVisible(false);
        jButton1 = new javax.swing.JButton();
        a1 = new javax.swing.JLabel();
        a1.setVisible(true);
        a2 = new javax.swing.JLabel();
        a2.setText("0");
        a3 = new javax.swing.JLabel();
        a3.setText("0");
        a4 = new javax.swing.JLabel();
        a4.setText("0");
        a5 = new javax.swing.JLabel();
        a5.setText("0");
        a6 = new javax.swing.JLabel();
        a6.setText("0");
        a7 = new javax.swing.JLabel();
        a7.setText("0");
        a8 = new javax.swing.JLabel();
        a8.setText("0");
        a9 = new javax.swing.JLabel();
        a9.setText("0");
        a10 = new javax.swing.JLabel();
        a10.setText("0");
        b1 = new javax.swing.JLabel();
        b1.setText("0");
        b2 = new javax.swing.JLabel();
        b2.setText("0");
        b3 = new javax.swing.JLabel();
        b3.setText("0");
        b4 = new javax.swing.JLabel();
        b4.setText("0");
        b5 = new javax.swing.JLabel();
        b5.setText("0");
        b6 = new javax.swing.JLabel();
        b6.setText("0");
        b7 = new javax.swing.JLabel();
        b7.setText("0");
        b8 = new javax.swing.JLabel();
        b8.setText("0");
        b9 = new javax.swing.JLabel();
        b9.setText("0");
        b10 = new javax.swing.JLabel();
        b10.setText("0");
        c1 = new javax.swing.JLabel();
        c1.setText("0");
        c2 = new javax.swing.JLabel();
        c2.setText("0");
        c3 = new javax.swing.JLabel();
        c3.setText("0");
        c4 = new javax.swing.JLabel();
        c4.setText("0");
        c5 = new javax.swing.JLabel();
        c5.setText("0");
        c6 = new javax.swing.JLabel();
        c6.setText("0");
        c7 = new javax.swing.JLabel();
        c7.setText("0");
        c8 = new javax.swing.JLabel();
        c8.setText("0");
        c9 = new javax.swing.JLabel();
        c9.setText("0");
        c10 = new javax.swing.JLabel();
        c10.setText("0");
        d1 = new javax.swing.JLabel();
        d1.setText("0");
        d2 = new javax.swing.JLabel();
        d2.setText("0");
        d3 = new javax.swing.JLabel();
        d3.setText("0");
        d4 = new javax.swing.JLabel();
        d4.setText("0");
        d5 = new javax.swing.JLabel();
        d5.setText("0");
        d6 = new javax.swing.JLabel();
        d6.setText("0");
        d7 = new javax.swing.JLabel();
        d7.setText("0");
        d8 = new javax.swing.JLabel();
        d8.setText("0");
        d9 = new javax.swing.JLabel();
        d9.setText("0");
        d10 = new javax.swing.JLabel();
        d10.setText("0");
        e1 = new javax.swing.JLabel();
        e1.setText("0");
        e2 = new javax.swing.JLabel();
        e2.setText("0");
        e3 = new javax.swing.JLabel();
        e3.setText("0");
        e4 = new javax.swing.JLabel();
        e4.setText("0");
        e5 = new javax.swing.JLabel();
        e5.setText("0");
        e6 = new javax.swing.JLabel();
        e6.setText("0");
        e7 = new javax.swing.JLabel();
        e7.setText("0");
        e8 = new javax.swing.JLabel();
        e8.setText("0");
        e9 = new javax.swing.JLabel();
        e9.setText("0");
        e10 = new javax.swing.JLabel();
        e10.setText("0");
        f1 = new javax.swing.JLabel();
        f1.setText("0");
        f2 = new javax.swing.JLabel();
        f2.setText("0");
        f3 = new javax.swing.JLabel();
        f3.setText("0");
        f4 = new javax.swing.JLabel();
        f4.setText("0");
        f5 = new javax.swing.JLabel();
        f5.setText("0");
        f6 = new javax.swing.JLabel();
        f6.setText("0");
        f7 = new javax.swing.JLabel();
        f7.setText("0");
        f8 = new javax.swing.JLabel();
        f8.setText("0");
        f9 = new javax.swing.JLabel();
        f9.setText("0");
        f10 = new javax.swing.JLabel();
        f10.setText("0");
        g1 = new javax.swing.JLabel();
        g1.setText("0");
        g2 = new javax.swing.JLabel();
        g2.setText("0");
        g3 = new javax.swing.JLabel();
        g3.setText("0");
        g4 = new javax.swing.JLabel();
        g4.setText("0");
        g5 = new javax.swing.JLabel();
        g5.setText("0");
        g6 = new javax.swing.JLabel();
        g6.setText("0");
        g7 = new javax.swing.JLabel();
        g7.setText("0");
        g8 = new javax.swing.JLabel();
        g8.setText("0");
        g9 = new javax.swing.JLabel();
        g9.setText("0");
        g10 = new javax.swing.JLabel();
        g10.setText("0");
        h1 = new javax.swing.JLabel();
        h1.setText("0");
        h2 = new javax.swing.JLabel();
        h2.setText("0");
        h3 = new javax.swing.JLabel();
        h3.setText("0");
        h4 = new javax.swing.JLabel();
        h4.setText("0");
        h5 = new javax.swing.JLabel();
        h5.setText("0");
        h6 = new javax.swing.JLabel();
        h6.setText("0");
        h7 = new javax.swing.JLabel();
        h7.setText("0");
        h8 = new javax.swing.JLabel();
        h8.setText("0");
        h9 = new javax.swing.JLabel();
        h9.setText("0");
        h10 = new javax.swing.JLabel();
        h10.setText("0");
        i1 = new javax.swing.JLabel();
        i1.setText("0");
        i2 = new javax.swing.JLabel();
        i2.setText("0");
        i3 = new javax.swing.JLabel();
        i3.setText("0");
        i4 = new javax.swing.JLabel();
        i4.setText("0");
        i5 = new javax.swing.JLabel();
        i5.setText("0");
        i6 = new javax.swing.JLabel();
        i6.setText("0");
        i7 = new javax.swing.JLabel();
        i7.setText("0");
        i8 = new javax.swing.JLabel();
        i8.setText("0");
        i9 = new javax.swing.JLabel();
        i9.setText("0");
        i10 = new javax.swing.JLabel();
        i10.setText("0");
        j1 = new javax.swing.JLabel();
        j1.setText("0");
        j2 = new javax.swing.JLabel();
        j2.setText("0");
        j3 = new javax.swing.JLabel();
        j3.setText("0");
        j4 = new javax.swing.JLabel();
        j4.setText("0");
        j5 = new javax.swing.JLabel();
        j5.setText("0");
        j6 = new javax.swing.JLabel();
        j6.setText("0");
        j7 = new javax.swing.JLabel();
        j7.setText("0");
        j8 = new javax.swing.JLabel();
        j8.setText("0");
        j9 = new javax.swing.JLabel();
        j9.setText("0");
        j10 = new javax.swing.JLabel();
        j10.setText("0");
        k1 = new javax.swing.JLabel();
        k1.setText("0");
        k2 = new javax.swing.JLabel();
        k2.setText("0");
        k3 = new javax.swing.JLabel();
        k3.setText("0");
        k4 = new javax.swing.JLabel();
        k4.setText("0");
        k5 = new javax.swing.JLabel();
        k5.setText("0");
        k6 = new javax.swing.JLabel();
        k6.setText("0");
        k7 = new javax.swing.JLabel();
        k7.setText("0");
        k8 = new javax.swing.JLabel();
        k8.setText("0");
        k9 = new javax.swing.JLabel();
        k9.setText("0");
        k10 = new javax.swing.JLabel();
        k10.setText("0");
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TF2 = new javax.swing.JTextField();
        CB2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        TF3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        multiply = new javax.swing.JLabel();
        temp1 = new javax.swing.JScrollPane();
        part1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        part2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        part3 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        part4 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        part5 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        part6 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        part7 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        part8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        part9 = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        part10 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        point2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Add Element Through the following Drop-Down Box-");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 410, -1));

        CB1.setMaximumRowCount(15);
        CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra" }));
        CB1.setToolTipText("Please Select an Element From The Drop-Down Box.");
        getContentPane().add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 70, -1));

        jLabel2.setText("Enter the base subscript -");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, -1));

        off1.setText("1");
        off1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                off1ActionPerformed(evt);
            }
        });
        getContentPane().add(off1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 40, -1));

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("Times New Roman", 1, 22)); // NOI18N
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setAutoscrolls(false);
        jScrollPane1.setViewportView(TextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 990, 40));

        point1.setText("1");
        getContentPane().add(point1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 10, -1));

        jButton1.setText("+");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        a1.setText("0");
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        a2.setText("0");
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        a3.setText("0");
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        a4.setText("0");
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, -1));

        a5.setText("0");
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        a6.setText("0");
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        a7.setText("0");
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        a8.setText("0");
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        a9.setText("0");
        getContentPane().add(a9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        a10.setText("0");
        getContentPane().add(a10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, 10));

        b1.setText("0");
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        b2.setText("0");
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        b3.setText("0");
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, -1));

        b4.setText("0");
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        b5.setText("0");
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        b6.setText("0");
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        b7.setText("0");
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        b8.setText("0");
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        b9.setText("0");
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        b10.setText("0");
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        c1.setText("0");
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        c2.setText("0");
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        c3.setText("0");
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        c4.setText("0");
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, -1));

        c5.setText("0");
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        c6.setText("0");
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        c7.setText("0");
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        c8.setText("0");
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, -1, -1));

        c9.setText("0");
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        c10.setText("0");
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, -1));

        d1.setText("0");
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        d2.setText("0");
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        d3.setText("0");
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        d4.setText("0");
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, -1));

        d5.setText("0");
        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        d6.setText("0");
        getContentPane().add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        d7.setText("0");
        getContentPane().add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        d8.setText("0");
        getContentPane().add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        d9.setText("0");
        getContentPane().add(d9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        d10.setText("0");
        getContentPane().add(d10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        e1.setText("0");
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        e2.setText("0");
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        e3.setText("0");
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, -1, -1));

        e4.setText("0");
        getContentPane().add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        e5.setText("0");
        getContentPane().add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        e6.setText("0");
        getContentPane().add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, -1, -1));

        e7.setText("0");
        getContentPane().add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, -1, -1));

        e8.setText("0");
        getContentPane().add(e8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, -1, -1));

        e9.setText("0");
        getContentPane().add(e9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, -1, -1));

        e10.setText("0");
        getContentPane().add(e10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        f1.setText("0");
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        f2.setText("0");
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        f3.setText("0");
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        f4.setText("0");
        getContentPane().add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        f5.setText("0");
        getContentPane().add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        f6.setText("0");
        getContentPane().add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));

        f7.setText("0");
        getContentPane().add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        f8.setText("0");
        getContentPane().add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));

        f9.setText("0");
        getContentPane().add(f9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        f10.setText("0");
        getContentPane().add(f10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        g1.setText("0");
        getContentPane().add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, -1, -1));

        g2.setText("0");
        getContentPane().add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        g3.setText("0");
        getContentPane().add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        g4.setText("0");
        getContentPane().add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));

        g5.setText("0");
        getContentPane().add(g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, -1, -1));

        g6.setText("0");
        getContentPane().add(g6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, -1, -1));

        g7.setText("0");
        getContentPane().add(g7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        g8.setText("0");
        getContentPane().add(g8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, -1, -1));

        g9.setText("0");
        getContentPane().add(g9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        g10.setText("0");
        getContentPane().add(g10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        h1.setText("0");
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        h2.setText("0");
        getContentPane().add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        h3.setText("0");
        getContentPane().add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));

        h4.setText("0");
        getContentPane().add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, -1, -1));

        h5.setText("0");
        getContentPane().add(h5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        h6.setText("0");
        getContentPane().add(h6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        h7.setText("0");
        getContentPane().add(h7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        h8.setText("0");
        getContentPane().add(h8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        h9.setText("0");
        getContentPane().add(h9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        h10.setText("0");
        getContentPane().add(h10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, -1));

        i1.setText("0");
        getContentPane().add(i1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

        i2.setText("0");
        getContentPane().add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        i3.setText("0");
        getContentPane().add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        i4.setText("0");
        getContentPane().add(i4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, -1, -1));

        i5.setText("0");
        getContentPane().add(i5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        i6.setText("0");
        getContentPane().add(i6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        i7.setText("0");
        getContentPane().add(i7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        i8.setText("0");
        getContentPane().add(i8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, -1, -1));

        i9.setText("0");
        getContentPane().add(i9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        i10.setText("0");
        getContentPane().add(i10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        j1.setText("0");
        getContentPane().add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        j2.setText("0");
        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        j3.setText("0");
        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, -1, -1));

        j4.setText("0");
        getContentPane().add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        j5.setText("0");
        getContentPane().add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, -1, -1));

        j6.setText("0");
        getContentPane().add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        j7.setText("0");
        getContentPane().add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        j8.setText("0");
        getContentPane().add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, -1, -1));

        j9.setText("0");
        getContentPane().add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        j10.setText("0");
        getContentPane().add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        k1.setText("0");
        getContentPane().add(k1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        k2.setText("0");
        getContentPane().add(k2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        k3.setText("0");
        getContentPane().add(k3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        k4.setText("0");
        getContentPane().add(k4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, -1, -1));

        k5.setText("0");
        getContentPane().add(k5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        k6.setText("0");
        getContentPane().add(k6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, -1));

        k7.setText("0");
        getContentPane().add(k7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        k8.setText("0");
        getContentPane().add(k8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        k9.setText("0");
        getContentPane().add(k9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, -1, -1));

        k10.setText("0");
        getContentPane().add(k10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, -1, -1));

        jButton2.setText("Add Element");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jButton3.setText("---------->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 90, -1));

        jLabel3.setText("Add any ion/complex through the following steps-");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 310, -1));

        jLabel4.setText("Enter the subscript for the complete ion-");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        TF2.setText("1");
        TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF2ActionPerformed(evt);
            }
        });
        getContentPane().add(TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 40, -1));

        CB2.setMaximumRowCount(15);
        CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "H", "He", "Li", "Be", "B", "C", "N", "O", "F", "Ne", "Na", "Mg", "Al", "Si", "P", "S", "Cl", "Ar", "K", "Ca", "Sc", "Ti", "V", "Cr", "Mn", "Fe", "Co", "Ni", "Cu", "Zn", "Ga", "Ge", "As", "Se", "Br", "Kr", "Rb", "Sr", "Y", "Zr", "Nb", "Mo", "Tc", "Ru", "Rh", "Pd", "Ag", "Cd", "In", "Sn", "Sb", "Te", "I", "Xe", "Cs", "Ba", "Hf", "Ta", "W", "Re", "Os", "Ir", "Pt", "Au", "Hg", "Tl", "Pb", "Bi", "Po", "At", "Rn", "Fr", "Ra" }));
        CB2.setToolTipText("Please Select an Element From The Drop-Down Box.");
        getContentPane().add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 70, -1));

        jLabel5.setText("Enter Subscript For This Element -");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        TF3.setText("1");
        getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 40, -1));

        jButton4.setText("Add Element in the ion/complex");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        jLabel6.setText("Ion/complex Formed so far -");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 30, 170, -1));

        TA2.setEditable(false);
        TA2.setColumns(20);
        TA2.setLineWrap(true);
        TA2.setRows(5);
        jScrollPane2.setViewportView(TA2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 50, 210, 50));

        jButton5.setText("Add Newly Formed Ion!");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, 210, -1));

        multiply.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        multiply.setText("1 X");
        getContentPane().add(multiply, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 50, -1, -1));

        part1.setColumns(20);
        part1.setRows(5);
        temp1.setViewportView(part1);

        getContentPane().add(temp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 190, 30));

        part2.setColumns(20);
        part2.setRows(5);
        jScrollPane3.setViewportView(part2);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 310, 190, 30));

        part3.setColumns(20);
        part3.setRows(5);
        jScrollPane4.setViewportView(part3);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 190, 30));

        part4.setColumns(20);
        part4.setRows(5);
        jScrollPane5.setViewportView(part4);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, 190, 30));

        part5.setColumns(20);
        part5.setRows(5);
        jScrollPane6.setViewportView(part5);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 190, 30));

        part6.setColumns(20);
        part6.setRows(5);
        jScrollPane7.setViewportView(part6);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 190, 30));

        part7.setColumns(20);
        part7.setRows(5);
        jScrollPane8.setViewportView(part7);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 190, 30));

        part8.setColumns(20);
        part8.setRows(5);
        jScrollPane9.setViewportView(part8);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 190, 30));

        part9.setColumns(20);
        part9.setRows(5);
        jScrollPane10.setViewportView(part9);

        getContentPane().add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 190, 30));

        part10.setColumns(20);
        part10.setRows(5);
        jScrollPane11.setViewportView(part10);

        getContentPane().add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 430, 190, 30));

        jButton6.setText("BALANCE THIS EQUATION!");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 230, 40));

        point2.setText("1");
        getContentPane().add(point2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 470, -1, -1));

        jButton7.setText("CLEAR ALL!");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, 210, 30));

        jButton8.setText("Developers");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 100, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void off1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_off1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_off1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int x=Integer.parseInt(point1.getText());
point1.setText(Integer.toString(x+1));
TextArea.append("+");// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int x=Integer.parseInt(point1.getText());
    point2.setText(""+x);
    
point1.setText(Integer.toString(x+1));
TextArea.append("---------->");// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
public int CheckStep(int k,javax.swing.JComboBox BOX_HOLD){
String previous="0";
int pointer=Integer.parseInt(point1.getText());
int ElementalIndex=BOX_HOLD.getSelectedIndex()+1;
int a11=Integer.parseInt(a1.getText());
int a22=Integer.parseInt(a2.getText());
int a33=Integer.parseInt(a3.getText());
int a44=Integer.parseInt(a4.getText());
int a55=Integer.parseInt(a5.getText());
int a66=Integer.parseInt(a6.getText());
int a77=Integer.parseInt(a7.getText());
int a88=Integer.parseInt(a8.getText());
int a99=Integer.parseInt(a9.getText());
int a1010=Integer.parseInt(a10.getText());
int found=0;

if(ElementalIndex==a11){found=1;
switch(pointer){
    case 1:previous=b1.getText();   b1.setText(""+k);break;
    case 2:previous=c1.getText();c1.setText(""+k);break;
    case 3:previous=d1.getText();d1.setText(""+k);break;
    case 4:previous=e1.getText();e1.setText(""+k);break;
    case 5:previous=f1.getText();f1.setText(""+k);break;
    case 6:previous=g1.getText();g1.setText(""+k);break;
    case 7:previous=h1.getText();h1.setText(""+k);break;
    case 8:previous=i1.getText();i1.setText(""+k);break;
    case 9:previous=j1.getText();j1.setText(""+k);break;
    case 10:previous=k1.getText();k1.setText(""+k);break;
}

}

if(ElementalIndex==a22){found=1;
switch(pointer){
    case 1:previous=b2.getText();b2.setText(""+k);break;
    case 2:previous=c2.getText();c2.setText(""+k);break;
    case 3:previous=d2.getText();d2.setText(""+k);break;
    case 4:previous=e2.getText();e2.setText(""+k);break;
    case 5:previous=f2.getText();f2.setText(""+k);break;
    case 6:previous=g2.getText();g2.setText(""+k);break;
    case 7:previous=h2.getText();h2.setText(""+k);break;
    case 8:previous=i2.getText();i2.setText(""+k);break;
    case 9:previous=j2.getText();j2.setText(""+k);break;
    case 10:previous=k2.getText();k2.setText(""+k);break;
}

}

if(ElementalIndex==a33){found=1;
switch(pointer){
    case 1:previous=b3.getText();b3.setText(""+k);break;
    case 2:previous=c3.getText();c3.setText(""+k);break;
    case 3:previous=d3.getText();d3.setText(""+k);break;
    case 4:previous=e3.getText();e3.setText(""+k);break;
    case 5:previous=f3.getText();f3.setText(""+k);break;
    case 6:previous=g3.getText();g3.setText(""+k);break;
    case 7:previous=h3.getText();h3.setText(""+k);break;
    case 8:previous=i3.getText();i3.setText(""+k);break;
    case 9:previous=j3.getText();j3.setText(""+k);break;
    case 10:previous=k3.getText();k3.setText(""+k);break;
}

}

if(ElementalIndex==a44){found=1;
switch(pointer){
    case 1:previous=b4.getText();b4.setText(""+k);break;
    case 2:previous=c4.getText();c4.setText(""+k);break;
    case 3:previous=d4.getText();d4.setText(""+k);break;
    case 4:previous=e4.getText();e4.setText(""+k);break;
    case 5:previous=f4.getText();f4.setText(""+k);break;
    case 6:previous=g4.getText();g4.setText(""+k);break;
    case 7:previous=h4.getText();h4.setText(""+k);break;
    case 8:previous=i4.getText();i4.setText(""+k);break;
    case 9:previous=j4.getText();j4.setText(""+k);break;
    case 10:previous=k4.getText();k4.setText(""+k);break;
}

}

if(ElementalIndex==a55){found=1;
switch(pointer){
    case 1:previous=b5.getText();b5.setText(""+k);break;
    case 2:previous=c5.getText();c5.setText(""+k);break;
    case 3:previous=d5.getText();d5.setText(""+k);break;
    case 4:previous=e5.getText();e5.setText(""+k);break;
    case 5:previous=f5.getText();f5.setText(""+k);break;
    case 6:previous=g5.getText();g5.setText(""+k);break;
    case 7:previous=h5.getText();h5.setText(""+k);break;
    case 8:previous=i5.getText();i5.setText(""+k);break;
    case 9:previous=j5.getText();j5.setText(""+k);break;
    case 10:previous=k5.getText();k5.setText(""+k);break;
}

}


if(ElementalIndex==a66){found=1;
switch(pointer){
    case 1:previous=b6.getText();b6.setText(""+k);break;
    case 2:previous=c6.getText();c6.setText(""+k);break;
    case 3:previous=d6.getText();d6.setText(""+k);break;
    case 4:previous=e6.getText();e6.setText(""+k);break;
    case 5:previous=f6.getText();f6.setText(""+k);break;
    case 6:previous=g6.getText();g6.setText(""+k);break;
    case 7:previous=h6.getText();h6.setText(""+k);break;
    case 8:previous=i6.getText();i6.setText(""+k);break;
    case 9:previous=j6.getText();j6.setText(""+k);break;
    case 10:previous=k6.getText();k6.setText(""+k);break;
}

}
if(ElementalIndex==a77){found=1;
switch(pointer){
    case 1:previous=b7.getText();b7.setText(""+k);break;
    case 2:previous=c7.getText();c7.setText(""+k);break;
    case 3:previous=d7.getText();d7.setText(""+k);break;
    case 4:previous=e7.getText();e7.setText(""+k);break;
    case 5:previous=f7.getText();f7.setText(""+k);break;
    case 6:previous=g7.getText();g7.setText(""+k);break;
    case 7:previous=h7.getText();h7.setText(""+k);break;
    case 8:previous=i7.getText();i7.setText(""+k);break;
    case 9:previous=j7.getText();j7.setText(""+k);break;
    case 10:previous=k7.getText();k7.setText(""+k);break;
}

}

if(ElementalIndex==a88){found=1;
switch(pointer){
    case 1:previous=b8.getText();b8.setText(""+k);break;
    case 2:previous=c8.getText();c8.setText(""+k);break;
    case 3:previous=d8.getText();d8.setText(""+k);break;
    case 4:previous=e8.getText();e8.setText(""+k);break;
    case 5:previous=f8.getText();f8.setText(""+k);break;
    case 6:previous=g8.getText();g8.setText(""+k);break;
    case 7:previous=h8.getText();h8.setText(""+k);break;
    case 8:previous=i8.getText();i8.setText(""+k);break;
    case 9:previous=j8.getText();j8.setText(""+k);break;
    case 10:previous=k8.getText();k8.setText(""+k);break;
}

}

if(ElementalIndex==a99){found=1;
switch(pointer){
    case 1:previous=b9.getText();b9.setText(""+k);break;
    case 2:previous=c9.getText();c9.setText(""+k);break;
    case 3:previous=d9.getText();d9.setText(""+k);break;
    case 4:previous=e9.getText();e9.setText(""+k);break;
    case 5:previous=f9.getText();f9.setText(""+k);break;
    case 6:previous=g9.getText();g9.setText(""+k);break;
    case 7:previous=h9.getText();h9.setText(""+k);break;
    case 8:previous=i9.getText();i9.setText(""+k);break;
    case 9:previous=j9.getText();j9.setText(""+k);break;
    case 10:previous=k9.getText();k9.setText(""+k);break;
}

}
if(ElementalIndex==a1010){found=1;
switch(pointer){
    case 1:previous=b10.getText();b10.setText(""+k);break;
    case 2:previous=c10.getText();c10.setText(""+k);break;
    case 3:previous=d10.getText();d10.setText(""+k);break;
    case 4:previous=e10.getText();e10.setText(""+k);break;
    case 5:previous=f10.getText();f10.setText(""+k);break;
    case 6:previous=g10.getText();g10.setText(""+k);break;
    case 7:previous=h10.getText();h10.setText(""+k);break;
    case 8:previous=i10.getText();i10.setText(""+k);break;
    case 9:previous=j10.getText();j10.setText(""+k);break;
    case 10:previous=k10.getText();k10.setText(""+k);break;
}

}
if(found==1){return Integer.parseInt(previous);}
if(found==0){
if(a11==0){a1.setText(""+ElementalIndex);}
else if(a22==0){a2.setText(""+ElementalIndex);}
else if(a33==0){a3.setText(""+ElementalIndex);}
else if(a44==0){a4.setText(""+ElementalIndex);}
else if(a55==0){a5.setText(""+ElementalIndex);}
else if(a66==0){a6.setText(""+ElementalIndex);}
else if(a77==0){a7.setText(""+ElementalIndex);}
else if(a88==0){a8.setText(""+ElementalIndex);}
else if(a99==0){a9.setText(""+ElementalIndex);}
else if(a1010==0){a10.setText(""+ElementalIndex);}

return 0;


}
return 0;


}

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if(off1.getText().equals("")){JOptionPane.showMessageDialog(null,"Please enter the base subscript!");}
       else {int previous_state;

int k2;
String temp="";
int k=Integer.parseInt(off1.getText());
previous_state=CheckStep(k,CB1);
k2=k+previous_state;
CheckStep(k2,CB1);
int ElementalIndex=CB1.getSelectedIndex()+1;


switch(ElementalIndex){
case 1:temp="H";break;
case 2:temp="He";break;
case 3:temp="Li";break;
case 4:temp="Be";break;
case 5:temp="B";break;
case 6:temp="C";break;
case 7:temp="N";break;
case 8:temp="O";break;
case 9:temp="F";break;
case 10:temp="Ne";break;
case 11:temp="Na";break;
case 12:temp="Mg";break;
case 13:temp="Al";break;
case 14:temp="Si";break;
case 15:temp="P";break;
case 16:temp="S";break;
case 17:temp="Cl";break;
case 18:temp="Ar";break;
case 19:temp="K";break;
case 20:temp="Ca";break;
case 21:temp="Sc";break;
case 22:temp="Ti";break;
case 23:temp="V";break;
case 24:temp="Cr";break;
case 25:temp="Mn";break;
case 26:temp="Fe";break;
case 27:temp="Co";break;
case 28:temp="Ni";break;
case 29:temp="Cu";break;
case 30:temp="Zn";break;
case 31:temp="Ga";break;
case 32:temp="Ge";break;
case 33:temp="As";break;
case 34:temp="Se";break;
case 35:temp="Br";break;
case 36:temp="Kr";break;
case 37:temp="Rb";break;
case 38:temp="Sr";break;
case 39:temp="Y";break;
case 40:temp="Zr";break;
case 41:temp="Nb";break;
case 42:temp="Mo";break;
case 43:temp="Tc";break;
case 44:temp="Ru";break;
case 45:temp="Rh";break;
case 46:temp="Pd";break;
case 47:temp="Ag";break;
case 48:temp="Cd";break;
case 49:temp="In";break;
case 50:temp="Sn";break;
case 51:temp="Sb";break;
case 52:temp="Te";break;
case 53:temp="I";break;
case 54:temp="Xe";break;
case 55:temp="Cs";break;
case 56:temp="Ba";break;
case 57:temp="Hf";break;
case 58:temp="Ta";break;
case 59:temp="W";break;
case 60:temp="Re";break;
case 61:temp="Os";break;
case 62:temp="Ir";break;
case 63:temp="Pt";break;
case 64:temp="Au";break;
case 65:temp="Hg";break;
case 66:temp="Tl";break;
case 67:temp="Pb";break;
case 68:temp="Bi";break;
case 69:temp="Po";break;
case 70:temp="At";break;
case 71:temp="Rn";break;
case 72:temp="Fr";break;
case 73:temp="Ra";break;
}


{if(k>1){TextArea.append(""+temp+k);} else {TextArea.append(temp);}}


int pointer=Integer.parseInt(point1.getText());
switch(pointer){
    case 1:{if(k>1){part1.append(""+temp+k);} else {part1.append(temp);}}break;
    case 2:{if(k>1){part2.append(""+temp+k);} else {part2.append(temp);}}break;
    case 3:{if(k>1){part3.append(""+temp+k);} else {part3.append(temp);}}break;   
    case 4:{if(k>1){part4.append(""+temp+k);} else {part4.append(temp);}}break;    
    case 5:{if(k>1){part5.append(""+temp+k);} else {part5.append(temp);}}break;   
    case 6:{if(k>1){part6.append(""+temp+k);} else {part6.append(temp);}}break;   
    case 7:{if(k>1){part7.append(""+temp+k);} else {part7.append(temp);}}break;          
    case 8:{if(k>1){part8.append(""+temp+k);} else {part8.append(temp);}}break;
    case 9:{if(k>1){part9.append(""+temp+k);} else {part9.append(temp);}}break;    
    case 10:{if(k>1){part10.append(""+temp+k);} else {part10.append(temp);}}break;   


}

off1.setText("1");}


// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
if((TF2.getText().equals(""))||(TF3.getText().equals(""))){JOptionPane.showMessageDialog(null,"Please input the required Values!");}
       else {      
  int k2k2;
int previous_state;
        multiply.setText(""+TF2.getText()+" X");
int k=Integer.parseInt(TF2.getText())*Integer.parseInt(TF3.getText());  
TF2.setEditable(false);
previous_state=CheckStep(k,CB2);
k2k2=k+previous_state;
CheckStep(k2k2,CB2);
String temp="";
int ElementalIndex=CB2.getSelectedIndex()+1;
int k2=Integer.parseInt(TF3.getText());
switch(ElementalIndex){
case 1:temp="H";break;
case 2:temp="He";break;
case 3:temp="Li";break;
case 4:temp="Be";break;
case 5:temp="B";break;
case 6:temp="C";break;
case 7:temp="N";break;
case 8:temp="O";break;
case 9:temp="F";break;
case 10:temp="Ne";break;
case 11:temp="Na";break;
case 12:temp="Mg";break;
case 13:temp="Al";break;
case 14:temp="Si";break;
case 15:temp="P";break;
case 16:temp="S";break;
case 17:temp="Cl";break;
case 18:temp="Ar";break;
case 19:temp="K";break;
case 20:temp="Ca";break;
case 21:temp="Sc";break;
case 22:temp="Ti";break;
case 23:temp="V";break;
case 24:temp="Cr";break;
case 25:temp="Mn";break;
case 26:temp="Fe";break;
case 27:temp="Co";break;
case 28:temp="Ni";break;
case 29:temp="Cu";break;
case 30:temp="Zn";break;
case 31:temp="Ga";break;
case 32:temp="Ge";break;
case 33:temp="As";break;
case 34:temp="Se";break;
case 35:temp="Br";break;
case 36:temp="Kr";break;
case 37:temp="Rb";break;
case 38:temp="Sr";break;
case 39:temp="Y";break;
case 40:temp="Zr";break;
case 41:temp="Nb";break;
case 42:temp="Mo";break;
case 43:temp="Tc";break;
case 44:temp="Ru";break;
case 45:temp="Rh";break;
case 46:temp="Pd";break;
case 47:temp="Ag";break;
case 48:temp="Cd";break;
case 49:temp="In";break;
case 50:temp="Sn";break;
case 51:temp="Sb";break;
case 52:temp="Te";break;
case 53:temp="I";break;
case 54:temp="Xe";break;
case 55:temp="Cs";break;
case 56:temp="Ba";break;
case 57:temp="Hf";break;
case 58:temp="Ta";break;
case 59:temp="W";break;
case 60:temp="Re";break;
case 61:temp="Os";break;
case 62:temp="Ir";break;
case 63:temp="Pt";break;
case 64:temp="Au";break;
case 65:temp="Hg";break;
case 66:temp="Tl";break;
case 67:temp="Pb";break;
case 68:temp="Bi";break;
case 69:temp="Po";break;
case 70:temp="At";break;
case 71:temp="Rn";break;
case 72:temp="Fr";break;
case 73:temp="Ra";break;
}
if(k2>1){
TA2.append(""+temp+k2);}
else {TA2.append(temp);}
TF3.setText("1");}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
TF2.setEditable(true);
int x=Integer.parseInt(TF2.getText());

{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();TextArea.append(complex);}else {TextArea.append(TA2.getText());}}

int pointer=Integer.parseInt(point1.getText());

switch(pointer){
case 1:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part1.append(complex);}else {part1.append(TA2.getText());}}break;
case 2:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part2.append(complex);}else {part2.append(TA2.getText());}}break;
case 3:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part3.append(complex);}else {part3.append(TA2.getText());}}break;
case 4:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part4.append(complex);}else {part4.append(TA2.getText());}}break;
case 5:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part5.append(complex);}else {part5.append(TA2.getText());}}break;
case 6:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part6.append(complex);}else {part6.append(TA2.getText());}}break;
case 7:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part7.append(complex);}else {part7.append(TA2.getText());}}break;
case 8:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part8.append(complex);}else {part8.append(TA2.getText());}}break;
case 9:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part9.append(complex);}else {part9.append(TA2.getText());}}break;
case 10:{if(x>1){String complex="("+TA2.getText()+")"+TF2.getText();part10.append(complex);}else {part10.append(TA2.getText());}}break;
    }
multiply.setText("1 X");
TA2.setText("");
TF2.setText("1");



// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// I don't know why but i hate this code!!!
                                        
int final1=0,final2=0,final3=0,final4=0,final5=0,final6=0,final7=0,final8=0,final9=0,final10=0;
 int LHS=Integer.parseInt(point2.getText())-1;
int out_arrow=LHS;
String arrow1="",arrow2="",arrow3="",arrow4="",arrow5="",arrow6="",arrow7="",arrow8="",arrow9="";
switch(out_arrow){
    case 0:arrow1="---------->";break;
    case 1:arrow2="---------->";break;
    case 2:arrow3="---------->";break;
    case 3:arrow4="---------->";break;
    case 4:arrow5="---------->";break;
    case 5:arrow6="---------->";break;
    case 6:arrow7="---------->";break;
    case 7:arrow8="---------->";break;
    case 8:arrow9="---------->";break;
    
        


}
int b11=Integer.parseInt(b1.getText());
int c11=Integer.parseInt(c1.getText());
int d11=Integer.parseInt(d1.getText());
int e11=Integer.parseInt(e1.getText());
int f11=Integer.parseInt(f1.getText());
int g11=Integer.parseInt(g1.getText());
int h11=Integer.parseInt(h1.getText());
int i11=Integer.parseInt(i1.getText());
int j11=Integer.parseInt(j1.getText());
int k11=Integer.parseInt(k1.getText());

int b22=Integer.parseInt(b2.getText());
int c22=Integer.parseInt(c2.getText());
int d22=Integer.parseInt(d2.getText());
int e22=Integer.parseInt(e2.getText());
int f22=Integer.parseInt(f2.getText());
int g22=Integer.parseInt(g2.getText());
int h22=Integer.parseInt(h2.getText());
int i22=Integer.parseInt(i2.getText());
int j22=Integer.parseInt(j2.getText());
int k22=Integer.parseInt(k2.getText());

int b33=Integer.parseInt(b3.getText());
int c33=Integer.parseInt(c3.getText());
int d33=Integer.parseInt(d3.getText());
int e33=Integer.parseInt(e3.getText());
int f33=Integer.parseInt(f3.getText());
int g33=Integer.parseInt(g3.getText());
int h33=Integer.parseInt(h3.getText());
int i33=Integer.parseInt(i3.getText());
int j33=Integer.parseInt(j3.getText());
int k33=Integer.parseInt(k3.getText());

int b44=Integer.parseInt(b4.getText());
int c44=Integer.parseInt(c4.getText());
int d44=Integer.parseInt(d4.getText());
int e44=Integer.parseInt(e4.getText());
int f44=Integer.parseInt(f4.getText());
int g44=Integer.parseInt(g4.getText());
int h44=Integer.parseInt(h4.getText());
int i44=Integer.parseInt(i4.getText());
int j44=Integer.parseInt(j4.getText());
int k44=Integer.parseInt(k4.getText());

int b55=Integer.parseInt(b5.getText());
int c55=Integer.parseInt(c5.getText());
int d55=Integer.parseInt(d5.getText());
int e55=Integer.parseInt(e5.getText());
int f55=Integer.parseInt(f5.getText());
int g55=Integer.parseInt(g5.getText());
int h55=Integer.parseInt(h5.getText());
int i55=Integer.parseInt(i5.getText());
int j55=Integer.parseInt(j5.getText());
int k55=Integer.parseInt(k5.getText());

int b66=Integer.parseInt(b6.getText());
int c66=Integer.parseInt(c6.getText());
int d66=Integer.parseInt(d6.getText());
int e66=Integer.parseInt(e6.getText());
int f66=Integer.parseInt(f6.getText());
int g66=Integer.parseInt(g6.getText());
int h66=Integer.parseInt(h6.getText());
int i66=Integer.parseInt(i6.getText());
int j66=Integer.parseInt(j6.getText());
int k66=Integer.parseInt(k6.getText());

int b77=Integer.parseInt(b7.getText());
int c77=Integer.parseInt(c7.getText());
int d77=Integer.parseInt(d7.getText());
int e77=Integer.parseInt(e7.getText());
int f77=Integer.parseInt(f7.getText());
int g77=Integer.parseInt(g7.getText());
int h77=Integer.parseInt(h7.getText());
int i77=Integer.parseInt(i7.getText());
int j77=Integer.parseInt(j7.getText());
int k77=Integer.parseInt(k7.getText());

int b88=Integer.parseInt(b8.getText());
int c88=Integer.parseInt(c8.getText());
int d88=Integer.parseInt(d8.getText());
int e88=Integer.parseInt(e8.getText());
int f88=Integer.parseInt(f8.getText());
int g88=Integer.parseInt(g8.getText());
int h88=Integer.parseInt(h8.getText());
int i88=Integer.parseInt(i8.getText());
int j88=Integer.parseInt(j8.getText());
int k88=Integer.parseInt(k8.getText());

int b99=Integer.parseInt(b9.getText());
int c99=Integer.parseInt(c9.getText());
int d99=Integer.parseInt(d9.getText());
int e99=Integer.parseInt(e9.getText());
int f99=Integer.parseInt(f9.getText());
int g99=Integer.parseInt(g9.getText());
int h99=Integer.parseInt(h9.getText());
int i99=Integer.parseInt(i9.getText());
int j99=Integer.parseInt(j9.getText());
int k99=Integer.parseInt(k9.getText());

int b1010=Integer.parseInt(b10.getText());
int c1010=Integer.parseInt(c10.getText());
int d1010=Integer.parseInt(d10.getText());
int e1010=Integer.parseInt(e10.getText());
int f1010=Integer.parseInt(f10.getText());
int g1010=Integer.parseInt(g10.getText());
int h1010=Integer.parseInt(h10.getText());
int i1010=Integer.parseInt(i10.getText());
int j1010=Integer.parseInt(j10.getText());
int k1010=Integer.parseInt(k10.getText());
int loop_time;
if((d11+d22+d33+d44+d55+d66+d77+d88+d99+d1010==0)){loop_time=2;}
else if((e11+e22+e33+e44+e55+e66+e77+e88+e99+e1010==0)){loop_time=3;}
else if((f11+f22+f33+f44+f55+f66+f77+f88+f99+f1010)==0){loop_time=4;}
else if(g11+g22+g33+g44+g55+g66+g77+g88+g99+g1010==0){loop_time=5;}
else if(h11+h22+h33+h44+h55+h66+h77+h88+h99+h1010==0){loop_time=6;}
else if(i11+i22+i33+i44+i55+i66+i77+i88+i99+i1010==0){loop_time=7;}
else if(j11+j22+j33+j44+j55+j66+j77+j88+j99+j1010==0){loop_time=8;}
else if(k11+k22+k33+k44+k55+k66+k77+k88+k99+k1010==0){loop_time=9;}
else {loop_time=10;}

if(loop_time==2){int done=0;int x3=0,x4=0,x5=0,x6=0,x7=0,x8=0,x9=0,x10=0;
for(int x1=1;x1<=199;x1++){if(done==1)break;
for(int x2=1;x2<=199;x2++){if(done==1)break;

 int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}
}
}
String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText();

JOptionPane.showMessageDialog(null,""+one+two);
TextArea.setText(""+one+two);

}



if(loop_time==3){int done=0; int x4=0,x5=0,x6=0,x7=0,x8=0,x9=0,x10=0;
for(int x1=1;x1<=100;x1++){if(done==1)break;
for(int x2=1;x2<=100;x2++){if(done==1)break;
for(int x3=1;x3<=100;x3++){if(done==1)break;

int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}




}

}

}

String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText();

JOptionPane.showMessageDialog(null,""+one+two+three);
TextArea.setText(""+one+two+three);





}
if(loop_time==4){int done=0;int x5=0,x6=0,x7=0,x8=0,x9=0,x10=0;
for(int x1=1;x1<=100;x1++){if(done==1)break;
for(int x2=1;x2<=100;x2++){if(done==1)break;
for(int x3=1;x3<=100;x3++){if(done==1)break;
for(int x4=1;x4<=100;x4++){if(done==1)break;
int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}





}



}


}



}


String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText();
JOptionPane.showMessageDialog(null,""+one+two+three+four);
TextArea.setText(""+one+two+three+four);


}
if(loop_time==5){int done=0;int x6=0,x7=0,x8=0,x9=0,x10=0;
for(int x1=1;x1<=45;x1++){if(done==1)break;
for(int x2=1;x2<=45;x2++){if(done==1)break;
for(int x3=1;x3<=45;x3++){if(done==1)break;
for(int x4=1;x4<=45;x4++){if(done==1)break;
for(int x5=1;x5<=45;x5++){if(done==1)break;
int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}





}



}




}





}




}

String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText()+"+"+arrow4;
String five=""+final5+part5.getText();
JOptionPane.showMessageDialog(null,""+one+two+three+four+five);
TextArea.setText(""+one+two+three+four+five);


}


if(loop_time==6){int done=0;int x7=0,x8=0,x9=0,x10=0;
for(int x1=1;x1<=25;x1++){if(done==1)break;
for(int x2=1;x2<=25;x2++){if(done==1)break;
for(int x3=1;x3<=25;x3++){if(done==1)break;
for(int x4=1;x4<=25;x4++){if(done==1)break;
for(int x5=1;x5<=25;x5++){if(done==1)break;
for(int x6=1;x6<=25;x6++){if(done==1)break;
int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}



}


}


}

}

}



}String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText()+"+"+arrow4;
String five=""+final5+part5.getText()+"+"+arrow5;
String six=""+final6+part6.getText();
JOptionPane.showMessageDialog(null,""+one+two+three+four+five+six);
TextArea.setText(""+one+two+three+four+five+six);




}
if(loop_time==7){int done=0; int x8=0,x9=0,x10=0;
for(int x1=1;x1<=15;x1++){if(done==1)break;
for(int x2=1;x2<=15;x2++){if(done==1)break;
for(int x3=1;x3<=15;x3++){if(done==1)break;
for(int x4=1;x4<=15;x4++){if(done==1)break;
for(int x5=1;x5<=15;x5++){if(done==1)break;
for(int x6=1;x6<=15;x6++){if(done==1)break;
for(int x7=1;x7<=15;x7++){if(done==1)break;

int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}

}

}

}

}

}



}


}


String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText()+"+"+arrow4;
String five=""+final5+part5.getText()+"+"+arrow5;
String six=""+final6+part6.getText()+"+"+arrow6;
String seven=""+final7+part7.getText();
JOptionPane.showMessageDialog(null,""+one+two+three+four+five+six+seven);
TextArea.setText(""+one+two+three+four+five+six+seven);






}
if(loop_time==8){int done=0;int x9=0,x10=0;
for(int x1=1;x1<=12;x1++){if(done==1)break;
for(int x2=1;x2<=12;x2++){if(done==1)break;
for(int x3=1;x3<=12;x3++){if(done==1)break;
for(int x4=1;x4<=12;x4++){if(done==1)break;
for(int x5=1;x5<=12;x5++){if(done==1)break;
for(int x6=1;x6<=12;x6++){if(done==1)break;
for(int x7=1;x7<=12;x7++){if(done==1)break;
for(int x8=1;x8<=12;x8++){if(done==1)break;
int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}






}



}

}

}

}

}



}


}

String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText()+"+"+arrow4;
String five=""+final5+part5.getText()+"+"+arrow5;
String six=""+final6+part6.getText()+"+"+arrow6;
String seven=""+final7+part7.getText()+"+"+arrow7;
String eight=""+final8+part8.getText();
JOptionPane.showMessageDialog(null,""+one+two+three+four+five+six+seven+eight);
TextArea.setText(""+one+two+three+four+five+six+seven+eight);




}
if(loop_time==9){int done=0;int x10=0;

for(int x1=1;x1<=9;x1++){if(done==1)break;
for(int x2=1;x2<=9;x2++){if(done==1)break;
for(int x3=1;x3<=9;x3++){if(done==1)break;
for(int x4=1;x4<=9;x4++){if(done==1)break;
for(int x5=1;x5<=9;x5++){if(done==1)break;
for(int x6=1;x6<=9;x6++){if(done==1)break;
for(int x7=1;x7<=9;x7++){if(done==1)break;
for(int x8=1;x8<=9;x8++){if(done==1)break;
for(int x9=1;x9<=9;x9++){if(done==1)break;
 int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}



}


}



}

}

}

}

}



}


}String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText()+"+"+arrow4;
String five=""+final5+part5.getText()+"+"+arrow5;
String six=""+final6+part6.getText()+"+"+arrow6;
String seven=""+final7+part7.getText()+"+"+arrow7;
String eight=""+final8+part8.getText()+"+"+arrow8;
String nine=""+final9+part9.getText();
JOptionPane.showMessageDialog(null,""+one+two+three+four+five+six+seven+eight+nine);
TextArea.setText(""+one+two+three+four+five+six+seven+eight+nine);






}



if(loop_time==10){
int done=0;
for(int x1=1;x1<=7;x1++){ if(done==1)break;
for(int x2=1;x2<=7;x2++){if(done==1)break;
for(int x3=1;x3<=7;x3++){if(done==1)break;
for(int x4=1;x4<=7;x4++){if(done==1)break;
for(int x5=1;x5<=7;x5++){if(done==1)break;
for(int x6=1;x6<=7;x6++){if(done==1)break;
for(int x7=1;x7<=7;x7++){if(done==1)break;
for(int x8=1;x8<=7;x8++){if(done==1)break;
for(int x9=1;x9<=7;x9++){if(done==1)break;
for(int x10=1;x10<=7;x10++){if(done==1)break;
//Innermost Powerful Loop By Vikrant.
 int no1[]={x1*b11,x2*c11,x3*d11,x4*e11,x5*f11,x6*g11,x7*h11,x8*i11,x9*j11,x10*k11};
 int no2[]={x1*b22,x2*c22,x3*d22,x4*e22,x5*f22,x6*g22,x7*h22,x8*i22,x9*j22,x10*k22};
 int no3[]={x1*b33,x2*c33,x3*d33,x4*e33,x5*f33,x6*g33,x7*h33,x8*i33,x9*j33,x10*k33};
 int no4[]={x1*b44,x2*c44,x3*d44,x4*e44,x5*f44,x6*g44,x7*h44,x8*i44,x9*j44,x10*k44};
 int no5[]={x1*b55,x2*c55,x3*d55,x4*e55,x5*f55,x6*g55,x7*h55,x8*i55,x9*j55,x10*k55};
 int no6[]={x1*b66,x2*c66,x3*d66,x4*e66,x5*f66,x6*g66,x7*h66,x8*i66,x9*j66,x10*k66};
 int no7[]={x1*b77,x2*c77,x3*d77,x4*e77,x5*f77,x6*g77,x7*h77,x8*i77,x9*j77,x10*k77};
 int no8[]={x1*b88,x2*c88,x3*d88,x4*e88,x5*f88,x6*g88,x7*h88,x8*i88,x9*j88,x10*k88};
 int no9[]={x1*b99,x2*c99,x3*d99,x4*e99,x5*f99,x6*g99,x7*h99,x8*i99,x9*j99,x10*k99};
int no10[]={x1*b1010,x2*c1010,x3*d1010,x4*e1010,x5*f1010,x6*g1010,x7*h1010,x8*i1010,x9*j1010,x10*k1010};
int l1=0,l2=0,l3=0,l4=0,l5=0,l6=0,l7=0,l8=0,l9=0,l10=0;
int r1=0,r2=0,r3=0,r4=0,r5=0,r6=0,r7=0,r8=0,r9=0,r10=0;
int i;
for( i=0;i<=LHS;i++){
 l1=l1+no1[i];
 l2=l2+no2[i];
 l3=l3+no3[i];
 l4=l4+no4[i];
 l5=l5+no5[i];
 l6=l6+no6[i];
 l7=l7+no7[i];
 l8=l8+no8[i];
 l9=l9+no9[i];
 l10=l10+no10[i];
    }

while(i<10){
 r1=r1+no1[i];
 r2=r2+no2[i];
 r3=r3+no3[i];
 r4=r4+no4[i];
 r5=r5+no5[i];
 r6=r6+no6[i];
 r7=r7+no7[i];
 r8=r8+no8[i];
 r9=r9+no9[i];
 r10=r10+no10[i];   
   
i=i+1;
}
if((l1==r1)&&(l2==r2)&&(l3==r3)&&(l4==r4)&&(l5==r5)&&(l6==r6)&&(l7==r7)&&(l8==r8)&&(l9==r9)&&(l10==r10)){
done=1;
final1=x1;
final2=x2;
final3=x3;
final4=x4;
final5=x6;
final7=x7;
final8=x8;
final9=x9;
final10=x10;
}





}
}
}
}
}
}
}      
}  
}

}
String one=""+final1+part1.getText()+"+"+arrow1;
String two=""+final2+part2.getText()+"+"+arrow2;
String three=""+final3+part3.getText()+"+"+arrow3;
String four=""+final4+part4.getText()+"+"+arrow4;
String five=""+final5+part5.getText()+"+"+arrow5;
String six=""+final6+part6.getText()+"+"+arrow6;
String seven=""+final7+part7.getText()+"+"+arrow7;
String eight=""+final8+part8.getText()+"+"+arrow8;
String nine=""+final9+part9.getText()+"+"+arrow9;
String ten=""+final10+part10.getText()+" ";
JOptionPane.showMessageDialog(null,""+one+two+three+four+five+six+seven+eight+nine+ten);
TextArea.setText(""+one+two+three+four+five+six+seven+eight+nine+ten);




}












//Useless code ends!!!








// TODO add your handling code here:
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        TextArea.setText("");
        TF2.setText("1");
        TA2.setText("");
        multiply.setText(""+"1"+" X");
        part1.setText("");
        part2.setText("");
        part3.setText("");
        part4.setText("");
        part5.setText("");
        part6.setText("");
        part7.setText("");
        part8.setText("");
        part9.setText("");
        part10.setText("");
        point1.setText("1");
        point2.setText("1");
        a1.setText("0");
        a2.setText("0");
        a3.setText("0");
        a4.setText("0");
        a5.setText("0");
        a6.setText("0");
        a7.setText("0");
        a8.setText("0");
        a9.setText("0");
        a10.setText("0");
        b1.setText("0");
        b2.setText("0");
        b3.setText("0");
        b4.setText("0");
        b5.setText("0");
        b6.setText("0");
        b7.setText("0");
        b8.setText("0");
        b9.setText("0");
        b10.setText("0");
        c1.setText("0");
        c2.setText("0");
        c3.setText("0");
        c4.setText("0");
        c5.setText("0");
        c6.setText("0");
        c7.setText("0");
        c8.setText("0");
        c9.setText("0");
        c10.setText("0");
        d1.setText("0");
        d2.setText("0");
        d3.setText("0");
        d4.setText("0");
        d5.setText("0");
        d6.setText("0");
        d7.setText("0");
        d8.setText("0");
        d9.setText("0");
        d10.setText("0");
        e1.setText("0");
        e2.setText("0");
        e3.setText("0");
        e4.setText("0");
        e5.setText("0");
        e6.setText("0");
        e7.setText("0");
        e8.setText("0");
        e9.setText("0");
        e10.setText("0");
        f1.setText("0");
        f2.setText("0");
        f3.setText("0");
        f4.setText("0");
        f5.setText("0");
        f6.setText("0");
        f7.setText("0");
        f8.setText("0");
        f9.setText("0");
        f10.setText("0");
        g1.setText("0");
        g2.setText("0");
        g3.setText("0");
        g4.setText("0");
        g5.setText("0");
        g6.setText("0");
        g7.setText("0");
        g8.setText("0");
        g9.setText("0");
        g10.setText("0");
        h1.setText("0");
        h2.setText("0");
        h3.setText("0");
        h4.setText("0");
        h5.setText("0");
        h6.setText("0");
        h7.setText("0");
        h8.setText("0");
        h9.setText("0");
        h10.setText("0");
        i1.setText("0");
        i2.setText("0");
        i3.setText("0");
        i4.setText("0");
        i5.setText("0");
        i6.setText("0");
        i7.setText("0");
        i8.setText("0");
        i9.setText("0");
        i10.setText("0");
        j1.setText("0");
        j2.setText("0");
        j3.setText("0");
        j4.setText("0");
        j5.setText("0");
        j6.setText("0");
        j7.setText("0");
        j8.setText("0");
        j9.setText("0");
        j10.setText("0");
        k1.setText("0");
        k2.setText("0");
        k3.setText("0");
        k4.setText("0");
        k5.setText("0");
        k6.setText("0");
        k7.setText("0");
        k8.setText("0");
        k9.setText("0");
        k10.setText("0");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JOptionPane.showMessageDialog(null,"The application has been developed by - \n"
            + "Vikrant (1410991673) \n"
            + "Yash Bansal (1410991686)\n"
            + "Virain Garg (1410991679)\n"
            + "Vidit Garg (1410991668)\n"
            + "CSE J-02 Chitkara University Pb \n"
            + "2015");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CB1;
    private javax.swing.JComboBox CB2;
    private javax.swing.JTextArea TA2;
    private javax.swing.JTextField TF2;
    private javax.swing.JTextField TF3;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a10;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel a9;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b10;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel b9;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c10;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel c9;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d10;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel d9;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e10;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel e7;
    private javax.swing.JLabel e8;
    private javax.swing.JLabel e9;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f10;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JLabel f8;
    private javax.swing.JLabel f9;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g10;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel g9;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h10;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    private javax.swing.JLabel h9;
    private javax.swing.JLabel i1;
    private javax.swing.JLabel i10;
    private javax.swing.JLabel i2;
    private javax.swing.JLabel i3;
    private javax.swing.JLabel i4;
    private javax.swing.JLabel i5;
    private javax.swing.JLabel i6;
    private javax.swing.JLabel i7;
    private javax.swing.JLabel i8;
    private javax.swing.JLabel i9;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel k1;
    private javax.swing.JLabel k10;
    private javax.swing.JLabel k2;
    private javax.swing.JLabel k3;
    private javax.swing.JLabel k4;
    private javax.swing.JLabel k5;
    private javax.swing.JLabel k6;
    private javax.swing.JLabel k7;
    private javax.swing.JLabel k8;
    private javax.swing.JLabel k9;
    private javax.swing.JLabel multiply;
    private javax.swing.JTextField off1;
    private javax.swing.JTextArea part1;
    private javax.swing.JTextArea part10;
    private javax.swing.JTextArea part2;
    private javax.swing.JTextArea part3;
    private javax.swing.JTextArea part4;
    private javax.swing.JTextArea part5;
    private javax.swing.JTextArea part6;
    private javax.swing.JTextArea part7;
    private javax.swing.JTextArea part8;
    private javax.swing.JTextArea part9;
    private javax.swing.JLabel point1;
    private javax.swing.JLabel point2;
    private javax.swing.JScrollPane temp1;
    // End of variables declaration//GEN-END:variables
}
